language: node_js
node_js:  
  - 10
cache:
  directories:
    - node_modules
before_install:
  - npm i -g typescript
before_deploy:
  - rm .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master